### ISSUE TITLE
KEYPOD: Key Value Table Demo screen does not return to the demo screen

### ISSUE THREAD

**Issue by gjwgit** [anusii/keypod#102]
From the demo page:

![Image](https://github.com/anusii/keypod/assets/1681429/0a8617d3-ad67-4f72-bd85-85d28013ae5a)

Click KEY VALUE TABLE DEMO button to go to

![Image](https://github.com/anusii/keypod/assets/1681429/8396db33-7156-479d-9894-19cc51b6fc4d)

Click the back arrow returns to the Home screen rather than the Demo screen.

![Image](https://github.com/anusii/keypod/assets/1681429/0708e6ce-49c8-47ca-86e5-11aa8916899d)

It should return to the DEMO screen.

**Comment by cdawei** [comment]
> It should return to the DEMO screen.

The `Go back` button does this correctly. In other words, we need to make the back arrow to perform consistently with the `Go back` button. 

(PS: we seem to add a few `Go back` buttons here and there to avoid the use of the back arrow which is often automatically generated by flutter but does not work as we expected. Perhaps a better understanding of the navigation/routing mechnism in flutter can help us make better use of these back arrows.)

Related to https://github.com/anusii/solidpod/issues/159

**Comment by cdawei** [comment]
Fixed in pull request https://github.com/anusii/keypod/pull/106
