### ISSUE TITLE
KEY POD: Exception on startup

### ISSUE THREAD

**Issue by gjwgit** [anusii/keypod#107]
## Description

I start up the dev branch (and the PR branches), click CONTINUE or LOGIN and I get the following exception which needs to be caught or fixed:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:solidpod/src/solid/utils/rdf.dart': Failed assertion: line 73 pos 14: '!(dataMap[sub] as Map).containsKey(pre)': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      parseTTL (package:solidpod/src/solid/utils/rdf.dart:73:14)
#3      loadPrvTTL (package:solidpod/src/solid/utils/misc.dart:91:12)
<asynchronous suspension>
#4      KeyManager._loadIndKeyFile (package:solidpod/src/solid/utils/key_management.dart:500:17)
<asynchronous suspension>
#5      KeyManager.hasIndividualKey (package:solidpod/src/solid/utils/key_management.dart:394:7)
<asynchronous suspension>
#6      readPod (package:solidpod/src/solid/read_pod.dart:67:11)
<asynchronous suspension>
#7      HomeScreenState._writePrivateData (package:keypod/screens/home.dart:129:27)
<asynchronous suspension>
```

The GUI just shows:

![Image](https://github.com/anusii/keypod/assets/1681429/02c12eaa-242a-4ba5-b0e9-c0436af859a9)

**Comment by cdawei** [comment]
The error message indicates that there are at least two triples in the `data/key-value.ttl` file:
- (`subject1`, `predicate1`, `object1`)
- (`subject2`, `predicate2`, `object2`)

where:
- `subject1` = `subject2`, and
- `predicate1` = `predicate2`

In the `keypod` app `subject1` and `subject2` is the `webID`, and `predicate1` and `predicate2` are the keys in the two key-value pairs.

Therefore, duplicated keys in the saved key-value pairs (which shouldn't happen in `keypod` but we may miss some checks) could cause this exception.

@gjwgit do you have the stored key-value pairs for us to check this conjecture?

**Comment by gjwgit** [comment]
I don't have a ready way to decode outside of the app unfortunately.

**Comment by cdawei** [comment]
> I don't have a ready way to decode outside of the app unfortunately.

I see. May I have a look at the content of the `ind-keys.ttl` file in your `keypod` folder on the server (which webID did you use for the test)?  It seems the duplication might be in the `ind-keys.ttl` instead of `key-value.ttl`.

**Comment by gjwgit** [comment]
Feel free to have a look in `server/kayon-toga/keypod` on solid@solidcommunity.au. 

I'm not sure what I am looking for in the files.

**Comment by cdawei** [comment]
It looks like the `path` predicate got two objects: `keypod/data/keyvalue.ttl`, `keypod/data/key-value.ttl`

It would be good to figure out how this got written into `ind-keys.ttl`. Will have a look at the relevant code in `solidpod`.
```
<https://pods.solidcommunity.au/kayon-toga/keypod/data/key-value.ttl>
    appsTerms:path "keypod/data/keyvalue.ttl", "keypod/data/key-value.ttl";
    appsTerms:iv IV_BASE64_STRING;
    appsTerms:sessionKey ENCRYPTED_SESSION_KEY.
```

**Comment by gjwgit** [comment]
Thanks @cdawei. I took a copy of the errant `ind-keys.ttl` and edited to remove the `keyvalue.ttl` entry.

I can log in again!

**Comment by gjwgit** [comment]
Do we test for this issue on start up and perhaps avoid it in future - though unlikely to occur again?

**Comment by cdawei** [comment]
> Do we test for this issue on start up and perhaps avoid it in future - though unlikely to occur again?

This issue indicates that we managed to corrupted some data files on server (and this is useful information). Perhaps raising an exception when it happens?

Move it back to **In Progress**.

**Comment by cdawei** [comment]
Please put further discussion under https://github.com/anusii/solidpod/issues/167

**Comment by cdawei** [comment]
Superseded by https://github.com/anusii/solidpod/issues/167
