### ISSUE TITLE
KEYPOD: On login simply display a centered button to push to then load the data from Solid Pod.

### ISSUE THREAD

**Issue by gjwgit** [anusii/keypod#125]
Done and merged into gjw/123_refactor.

- [ ] Include text on button page: "You are not logged in" or "You are logged in with WebID".

**Comment by gjwgit** [comment]
@zheyxu could you review this implementation once we have the refactor merged into dev.

The current implementation is more complicated than it need to be - we used to have a whole other functionality int he app that we have now moved into the solidpod repo as the demopod. So there are some odd artifacts remaining int he implementation of KeyPod that do not make sense

Please review and propose simplification. Thanks.

**Comment by zheyxu** [comment]
Discussion:
1. Whether the first page after login is necessary? It is more convenient to go directly into second page (Security key enter page or key value pair table page),
<img width="800" alt="Screenshot 2024-07-19 at 10 00 45 AM" src="https://github.com/user-attachments/assets/2903304c-40ee-4d3c-bf9d-4cf9a84dbeb7">

**Comment by zheyxu** [comment]
Current plan is to remove the page and let user get to Kay pair table page directly after login. 
If user clicks Continue, user goes to a blank key pair table page.

**Comment by gjwgit** [comment]
Okay - let's remove the one button page.

**Comment by zheyxu** [comment]
Even if user click `Continue` button, the app still requires user to login in. @gjwgit

**Comment by gjwgit** [comment]
For keypod let's drop the Continue button now. That should be a simple config change in SolidLogin.

**Comment by zheyxu** [comment]
Made pr https://github.com/anusii/solidpod/pull/219
![Image](https://github.com/user-attachments/assets/b8029255-ad1d-46db-9075-ca2517c6be86)
