### ISSUE TITLE
KEYPOD: Report the WebID on login in the top left text area.

### ISSUE THREAD

**Issue by gjwgit** [anusii/keypod#130]
Currently it is a TODO message.

![Image](https://github.com/user-attachments/assets/67f41af3-8d56-470f-a1e0-6e320eefc815)

**Comment by gjwgit** [comment]
Notice it is done in demopod



![Image](https://github.com/user-attachments/assets/734e1841-c8d7-4550-a749-ee4c65ac1285)

Review how done there, do the same. Consider any opportunity to simplify by additions to solidpod package.

**Comment by zheyxu** [comment]
Is combined with https://github.com/anusii/keypod/issues/131
