### ISSUE TITLE
KEYPOD: Add WebID to the About popup

### ISSUE THREAD

**Issue by gjwgit** [anusii/keypod#131]
A user can not see their webID after logging in and would like to.

![Image](https://github.com/user-attachments/assets/85ad74fa-01a7-4585-bee6-1cb123ee9f8f)

**Comment by zheyxu** [comment]
Made some updates but it is better to create a pr after https://github.com/anusii/keypod/pull/129 is merged.

![Image](https://github.com/user-attachments/assets/02d5681a-45a7-45ec-aa39-3a3d9d957857)

**Comment by zheyxu** [comment]
But if user clicks `Continue` and go to KeyValueTable table, the Web ID is missing.

![Image](https://github.com/user-attachments/assets/243837ca-f3f1-43ca-b641-b2b3cf12d647)
![Image](https://github.com/user-attachments/assets/1180e8c8-43a1-403a-a872-0d9150de2cce)

**Comment by zheyxu** [comment]
Made pr https://github.com/anusii/keypod/pull/132
![Image](https://github.com/user-attachments/assets/c0ca061e-b80e-4125-9dc7-5cb93dbd5942)
