### ISSUE TITLE
KEYPOD: Add initial GUI for viewing data from POD

### ISSUE THREAD

**Issue by gjwgit** [anusii/keypod#28]
# Description

Replace the placeholder Text widget with a simple text view widget to display the current contents of the key-value-note data from the POD.

# Why

So that we have a very simple app that shows encrypted data reading from a POD.

**Comment by gjwgit** [comment]
This is blocked by https://github.com/anusii/solid/issues/2

**Comment by anushkavidanage** [comment]
A simple file browser on the home page

**Comment by gjwgit** [comment]
Displays the encryption key as a demo of private data obtained from the POD

**Comment by gjwgit** [comment]
Review this task today. There is some confusion. I have attempted to clarify in solidpod#77
