### ISSUE TITLE
KEYPOD: Add icon for all platforms

### ISSUE THREAD

**Issue by gjwgit** [anusii/keypod#42]
Use the keypod_logo.png as the icon.

**Comment by gjwgit** [comment]
Use flutter_launcher_icon to do the hard work?

**Comment by anushkavidanage** [comment]
Used the above package to add icons. PR https://github.com/anusii/keypod/pull/45

**Comment by zheyxu** [comment]
Test on MacOS,ios, android, web. All works well. For MacOS, it needs to run ```flutter clean``` first.

**Comment by gjwgit** [comment]
Tested on android - all good.
