### ISSUE TITLE
KEYPOD: Widget to view, insert, edit, delete rows of key-value pairs

### ISSUE THREAD

**Issue by gjwgit** [anusii/keypod#48]
## User Story

As a user of the keypod demo and template app the home screen will have a button view with two buttons and an about along the bottom. This will mimic a typical app that I as the app builder might construct.

The first button KEYPODS will be this new table display of the key value pairs, able to edit, save, delete the entries that are stored in my POD.

The second button TESTING is then the current Test page with miscellaneous testing buttons like it is now.

The ABOUT is aligned to the right and is the usual about popup.

## Depends

- [x] https://github.com/anusii/solidpod/issues/77
- [x] https://github.com/anusii/solidpod/issues/78

## Description

This milestone is to implement a simple widget in keypod that is displayed as the home page.

## Why

This will demonstrate the readPod and witePod functionality and will then essentially be the final KeyPod demonstrator app.

## Closing Criteria

- [x] App has two buttons KEYPODS and TESTING and an ABOUT button along the bottom.
- [x] The keypod page will display a table with two columns for a key and a value.
- [x] Two buttons are available LOAD and SAVE
- [x] If already logged into the solid pod (initial SolidLogin) the table is populated with data from the Solid Pod
- [x] If already logged into the solid pod (initial SolidLogin) the LOAD button is greyed out (data already loaded)
- [x] If **not** already logged into the solid pod (initial SolidLogin) the LOAD button is active
- [x] When the LOAD button is tapped it will call SolidLoginPopup to ensure the user is already logged in and then lload the data into the table.
- [x] If there is no data in the solid pod (e.g., expected data file not found) then table is empty and LOAD becomes greyed out
- [x]  Each row in the table can be deleted, edited
- [x] A new row can be inserted to add a new key-value entry
- [x] After any change is made to the data the SAVE button (originally greyed out) becomes active
- [x] Changes are saved to the Solid Pod when the SAVE button is tapped. 
- [x] The table can not be changed unless the LOAD button has been tapped. First time we have just an empty table.

**Comment by junhaow1** [comment]
demo: 
https://github.com/anusii/keypod/assets/37771259/669d3544-1e21-473c-bd89-0f0bdc44a214

**Comment by junhaow1** [comment]
working branch : https://github.com/anusii/keypod/tree/kev/48_table

**Comment by junhaow1** [comment]
demo: 
https://github.com/anusii/keypod/assets/37771259/d90dd211-49e0-456c-af59-c47c7ca208e8

**Comment by gjwgit** [comment]
Very nice. Great demo.  Good to get this into dev now.

We may want to create new issues for a few things you noted:

- [ ] Address the slowness of saving and loading - it should be a single write and a single read?
- [ ] Can the columns be sorted?

**Comment by cdawei** [comment]
Thanks Kevin for the interesting demo!

Regarding the slowness in read/write, if you are already using the current `dev` branch of `solidpod` which optimised the read/write speed (through [this PR](https://github.com/anusii/solidpod/pull/130)), perhaps try options below:
- Use release mode if the web app is in debug mode: `flutter build web --release`
- Use a different web renderer as list here https://docs.flutter.dev/platform-integration/web/renderers

And the flutter web build is likely slow in general, for example, see this discussion (an old thread but seems still relevant) https://github.com/flutter/flutter/issues/49058

**Comment by junhaow1** [comment]
> Thanks Kevin for the interesting demo!
> 
> Regarding the slowness in read/write, if you are already using the current `dev` branch of `solidpod` which optimised the read/write speed (through [this PR](https://github.com/anusii/solidpod/pull/130)), perhaps try options below:
> 
> * Use release mode if the web app is in debug mode: `flutter build web --release`
> * Use a different web renderer as list here https://docs.flutter.dev/platform-integration/web/renderers
> 
> And the flutter web build is likely slow in general, for example, see this discussion (an old thread but seems still relevant) [flutter/flutter#49058](https://github.com/flutter/flutter/issues/49058)

good point. testing now

**Comment by junhaow1** [comment]
flutter run -d chrome --release

is way quicker :) Thanks @cdawei 

new demo: 
https://github.com/anusii/keypod/assets/37771259/9d1ad9c9-7689-41b0-a2a4-70466ed68ec5

**Comment by junhaow1** [comment]
> Very nice. Great demo. Good to get this into dev now.
> 
> We may want to create new issues for a few things you noted:
> 
> * [x]  Address the slowness of saving and loading - it should be a single write and a single read?
> * [ ]  Can the columns be sorted?

ticket created https://github.com/anusii/keypod/issues/76
