### ISSUE TITLE
KEYPOD: Show busy pointer after click Show Private Data

### ISSUE THREAD

**Issue by gjwgit** [anusii/keypod#58]
## Description

After I click the Show Private Data there is a lag while the data is retrieved. It is not obvious that something is happening. A busy icon would be useful until the data is displayed.

**Comment by junhaow1** [comment]
https://github.com/anusii/keypod/assets/37771259/0b56967a-c4c6-4fc9-abb4-6ee7cddd4c88

**Comment by junhaow1** [comment]
https://github.com/anusii/keypod/pull/62 PR created 

- [ ] make prep

**Comment by junhaow1** [comment]
merged, can be closed
