### ISSUE TITLE
KEYPOD: Login animation on home page cannot be cancelled

### ISSUE THREAD

**Issue by cdawei** [anusii/keypod#59]
![Image](https://github.com/anusii/keypod/assets/13044715/18b7d6dd-db5e-427a-ae8f-b3b36e5afd76)
The animation is there forever and clicking the "Cancel" button seems to change nothing.

To reproduce:
1. Start the keypod app, click "Login" and log into a POD
2. In the home page, click the back arrow at the top left to go back to the login page
3. Click the "Login" button again

**Comment by cdawei** [comment]
This issue is likely related to #96

**Comment by cdawei** [comment]
No longer there in the latest `dev` branch, move to backlog

**Comment by gjwgit** [comment]
I've not noticed this issue lately either. @zheyxu will review.

**Comment by zheyxu** [comment]
Tested and find the issue is that if user first log in and click the return icon button. The app keeps login and not ask login information. The animation will keeps on the screen.

**Comment by cdawei** [comment]
The back arrow is not needed for the home page. Park this issue for the moment. Add a logout button for logging out the app.

**Comment by cdawei** [comment]
With pull request https://github.com/anusii/solidpod/pull/121, the animation can be cancelled by clicking the "Cancel" button. Ideally, the animation should disappear after successfully logging in.

To reproduce (with changes in https://github.com/anusii/solidpod/pull/121):
1. Start keypod and click "Login"
1. Click "Logout" at the top left corner of the test page
1. Click "Login" again

**Comment by zheyxu** [comment]
As logout function is implemented https://github.com/anusii/solidpod/issues/118, the issue can be closed.
