### ISSUE TITLE
KEYPOD: Split About Dialog into own file about.dart

### ISSUE THREAD

**Issue by gjwgit** [anusii/keypod#61]
## Description

Migrate the current showAboutDialog in home.dart to its own file about.dart

## So That

To unclutter home.dart and so reduce the number of lines in the file in accordance with style guidelines and to have a nice simple template app source code.

## Closing Criteria

- [ ] The app works just the same

**Comment by junhaow1** [comment]
https://github.com/anusii/keypod/pull/64 PR created

**Comment by junhaow1** [comment]
merged, can be closed
