### ISSUE TITLE
KEYPOD: Relocate installers

### ISSUE THREAD

**Issue by cdawei** [anusii/keypod#65]
Installers (binary files in the `installers/` folder) usually change in every release, so it may not be a good idea to put them in the git repository. 

A better option might be attaching them with a particular release of the main branch (GitHub allows to upload binary files when creating a release).

**Comment by gjwgit** [comment]
Thanks @cdawei Could you look into how this is best done? I populate my`installers` automatically from a Makefile/shell commands. It would be good to do the same through the github release mechanism.

Also, we will probably have two approaches, one is using github releases for major releases. The other is that we push intermediate releases to a web site for access by testers/developers for each minor release, which is where the `installers` directory comes in to play.

**Comment by cdawei** [comment]
Documentation from GitHub for reference:
- [GitHub releases](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases)
- [Moving a file in your repository to Git Large File Storage](https://docs.github.com/en/repositories/working-with-files/managing-large-files/moving-a-file-in-your-repository-to-git-large-file-storage)

**Comment by gjwgit** [comment]
On Ubuntu `wajig install git-lfs`

But then `git checkout dc/65_relocate_installers` then `git pull`. It complained

```
remote: Enumerating objects: 298, done.
remote: Counting objects: 100% (298/298), done.
remote: Compressing objects: 100% (156/156), done.
remote: Total 298 (delta 142), reused 298 (delta 142), pack-reused 0
Receiving objects: 100% (298/298), 35.92 KiB | 125.00 KiB/s, done.
Resolving deltas: 100% (142/142), completed with 5 local objects.
From github.com:anusii/keypod
 * [new branch]      dc/65_gitlfs_installers    -> origin/dc/65_gitlfs_installers
 + 164d986...f0af3d8 dev                        -> origin/dev  (forced update)
 + f8b4cdc...876ece9 zy/122_login_animation     -> origin/zy/122_login_animation  (forced update)
 + d936d19...5ca41c9 zy/59_indi_login_animation -> origin/zy/59_indi_login_animation  (forced update)
Your configuration specifies to merge with the ref 'refs/heads/dc/65_relocate_installers'
from the remote, but no such ref was fetched.
```
My installers is empty. So I recreated keypod.apk and added to repo then pushed. Not sure I am doing it correctly!

**Comment by cdawei** [comment]
> Your configuration specifies to merge with the ref 'refs/heads/dc/65_relocate_installers'
> from the remote, but no such ref was fetched.

Perhaps try `rebase` instead of `merge`, as suggested [here](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository#fully-removing-the-data-from-github).

**Comment by gjwgit** [comment]
oops. that fixed it. Thanks
