### ISSUE TITLE
KEYPOD: Add Logout button on the test page

### ISSUE THREAD

**Issue by cdawei** [anusii/keypod#69]
Implement a logout button on the test page (`home.dart`) for users to logging out the app. It should call the `logout` function from `solidpod`. This is the front end task for https://github.com/anusii/solidpod/issues/118

TODO:
- [ ] Add a logout button on page `home.dart`
- [ ] Remove the back arrow at the top-left of page `home.dart`

**Comment by gjwgit** [comment]
The proposed logoutPod button seems to then return to the login page.

If login for the app is not required, then it should stay on the same page, or even a page that is passed as a parameter?

If login is required for the app, then is should return to the login page unless it is overridden with a new page in the call.

**Comment by cdawei** [comment]
> The proposed logoutPod button seems to then return to the login page.
> 
>     *  If login for the app is not required, then it should stay on the same page, or even a page that is passed as a parameter?
>
>     *  If login is required for the app, then is should return to the login page unless it is overridden with a new page in the call.

A parametrised logout button (i.e., go to the provided child widget upon successfully logging out) sounds good to me. My question is whether `solidpod` should provide a logout button widget or a logout function. 
- A logout button might be easier for app developers to use but also restricts what they can do (e.g. they may want something other than a button)
- A logout function is more versatile but app devs need to write UI code to use the function. 

More discussion needed.
