### ISSUE TITLE
KEY POD: License is GPL not MIT - fix the source files.

### ISSUE THREAD

**Issue by gjwgit** [anusii/keypod#83]
I tend to make apps GPLv3 (so others that build on our freely given work in the app need to make their code freely available too if they distribute it)  and libraries MIT (so they can be freely used without the viral nature of the GPL)

The appropriate license is in license.dart (for dart file headers) and in LICENSE.

**Comment by junhaow1** [comment]
https://github.com/anusii/keypod/pull/88 PR created
