### ISSUE TITLE
KEY POD: Restructure the app to ready for release

### ISSUE THREAD

**Issue by gjwgit** [anusii/keypod#84]
## Description

In preparation for releasing the app change the work flow for KEY POD to be:

### SolidLogin page

- [X] As it currently is with: Login | Continue | Register | Info
- [x] Info link to keypod repo README.md)

### KeyValue Table

This becomes the first page (home) of the app

Replace Home button with Testing to go to the testing page.

### Testing page

Go Back to go back to the main app page

**Comment by junhaow1** [comment]
https://github.com/anusii/keypod/pull/92 PR created

**Comment by junhaow1** [comment]
demo: 

https://github.com/anusii/keypod/assets/37771259/37411861-1098-44a1-9e3e-f2349c6018c0

**Comment by gjwgit** [comment]
Looks great. Thanks @junhaow1.
