### ISSUE TITLE
KEYPOD: In the About dialog show my WebID

### ISSUE THREAD

**Issue by gjwgit** [anusii/keypod#97]
## User Story

As an end user I want to see my WebID that I logged in with somewhere. Perhaps a good place for it is in the About dialog, just before the Authors: put "Your WebID is: https://....."

![Image](https://github.com/anusii/keypod/assets/1681429/d03acd3e-5754-40f1-98db-071c80d4ebec)

**Comment by cdawei** [comment]
Will a user be able to click the About dialog without logging in (e.g. by clicking the `Continue` button to use the app)? The webID may not be available in this case.

**Comment by cdawei** [comment]
An alternative suggested by Anushka #101

**Comment by cdawei** [comment]
Superseded by #101
