### ISSUE TITLE
KEYPOD HOME: New LOGOUT button

### ISSUE THREAD

**Issue by gjwgit** [anusii/keypod#98]
Add a logout button up the top next to the About button in the Keypod app using a logout icon.

Same functionality as the "Forget Remote Solid Server Login Info" - presumably a single function call to `solidpod`.

**Comment by gjwgit** [comment]
Use a logout icon.

**Comment by cdawei** [comment]
Pull request https://github.com/anusii/keypod/pull/105 created
![logout](https://github.com/anusii/keypod/assets/13044715/0e26c98f-ea1e-41d6-a07d-2025b4f63859)
